### ISSUE TITLE
Flathub: outdated runtime

### ISSUE THREAD

**Issue by solopasha** [SeaDve/Mousai#72]
Hi, after running flatpak update, I saw the following:

> Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
>    The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
> Info: applications using this runtime:
>    io.github.seadve.Mousai

Is it possible to update the runtime? Thanks for your work & great app

**Comment by SeaDve** [comment]
Hi, thanks for reporting!

Mousai is actually already on 44 in the development branch. However, I don't think it is ready yet to publish to Flathub due to stability concerns.

On the other hand, the current stable version could easily be updated to 44 through https://github.com/flathub/io.github.seadve.Mousai. If someone has the time to make a PR and  test it, I'll be glad to merge it.
