### ISSUE TITLE
Use a symbolic icon in Adw.StatusPage

### ISSUE THREAD

**Issue by imhemish** [SeaDve/Mousai#78]
![image](https://user-images.githubusercontent.com/74466492/230707211-18892b07-f608-4bab-967b-40dbb4d5f4cb.png)

Its kind of a standard in gnome apps to use a symbolic icon in Status Page. Maybe use a symbolic icon?

**Comment by SeaDve** [comment]
It used to use a symbolic icon. However, I think it looks more alive this way. There are also other gnome apps that uses non symbolic icon, like Secrets.

Also, [HIG](https://developer.gnome.org/hig/patterns/feedback/placeholders.html) mentions that colorful/illustrative view are the following:

> Placeholder pages with the illustration style are primarily used in the main view of an app, when it is empty. The main purpose of doing this is to avoid an awkward empty state when the app is first used. This type of placeholder can be a good way to provide guidance, set a positive note, and establish a relationship with the user.

> If an illustration placeholder is used as part of the initial onboarding experience, the image should be rich and colorful, and the text should be positive and upbeat. This can also be an opportunity to strike up a relationship with the user by addressing them directly.

Preferably though, I'd like to use something more illustrative and colorful instead of the app icon itself.
